apiVersion: v1
kind: Service
metadata:
  name: {{ include "cartservice.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cartservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "cartservice.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
